#!/bin/sh

LOGIN="halvarez"

#installing packages
	apt -y git
	apt -y vim
	apt -y sudo
	apt -y curl
	apt -y wget

#add /usr/sbin to variable environment for all user
	 echo "Adding PATH /usr/sbin..."
	 echo "export PATH=$PATH:/usr/sbin" > /etc/profile.d/add_sbin.sh
	 source /etc/profile.d/add_sbin.sh
	 echo "/usr/sbin set ! :)"

#add user42 as group and LOGIN in user42
	 echo "Adding ${LOGIN} to sudo members..."
	 usermod -aG sudo ${LOGIN}
	 echo "${LOGIN} added to sudo ! :)"

